/* solver_ida.c -- Stage 3 final C: optimal 2x2x2 solver by IDA* (author's own)
 *
 * Authorship. The search (my_h, frame_t, my_search, my_solve), the ranking
 * (my_rank_perm, my_rank_ori), and the table builders (practice/my_tables.h,
 * practice/my_pdb.h) are the author's own, written in exercises 1-5 and moved
 * here unchanged except for the frame_t field order (see below). The glue
 * marked [glue] (constants, table declarations, input validation, replay
 * check, host main, target _start and ecalls) was assembled with AI help.
 *
 * Two builds from this one file:
 *
 *   Host:   cc -O2 -std=c99 solver_ida.c -o solver_ida
 *           ./solver_ida 21345671111111
 *       Builds the tables at start-up with the author's builders, same
 *       input/output as ../solver.c.
 *
 *   Target: make -C ../stage4 ref        (gcc -O2 -march=rv32i, see there)
 *       -DTARGET. No libc: the tables are linked from tables.s (.rodata,
 *       generated by gen_tables after gates H1 and H2), the input is the
 *       string `input` from input.s, output and exit go through Ripes ecalls.
 *       This is the reference build the hand-written assembly is measured
 *       against.
 *
 * Exit status: 0 solved and replay verified, 1 replay failed or no solution,
 * 2 invalid input. Define COUNT to keep the node counter (host analysis
 * only; it is a 64-bit add per node, so the measured builds leave it out).
 */
#include <stdint.h>

/* [glue] Constants and quarter-turn definitions, as in ../solver.c. */
enum { CUBIES = 7, PERMUTATIONS = 5040, ORIENTATIONS = 729, MOVES = 9 };
static const char *const move_names[MOVES] = {"R",  "R2", "R'", "B", "B2",
                                              "B'", "D",  "D2", "D'"};
static const uint8_t source[3][CUBIES] = {
    {1, 4, 2, 0, 3, 5, 6},
    {0, 1, 2, 4, 5, 6, 3},
    {0, 2, 5, 3, 1, 4, 6},
};
static const uint8_t twist[3][CUBIES] = {
    {1, 2, 0, 2, 1, 0, 0},
    {0, 0, 0, 1, 2, 1, 2},
    {0, 0, 0, 0, 0, 0, 0},
};

#ifdef TARGET
/* [glue] Tables from tables.s, under the names the author's code uses. */
extern const uint16_t perm_move[3][PERMUTATIONS];
extern const uint16_t ori_move[3][ORIENTATIONS];
extern const uint8_t pdb_p[PERMUTATIONS], pdb_o[ORIENTATIONS];
#define my_perm_move perm_move
#define my_ori_move ori_move
#define my_pdb_p pdb_p
#define my_pdb_o pdb_o

/* Author's ranking functions (exercise 1), as in practice/my_tables.h. */
static const uint16_t weight[CUBIES] = {720, 120, 24, 6, 2, 1, 1};

static uint16_t my_rank_perm(const uint8_t p[CUBIES])
{
    uint16_t rank = 0;
    for (uint8_t i = 0; i < CUBIES; ++i){
        for (uint8_t j = (uint8_t) (i + 1U); j < CUBIES; ++j){
            if (p[j] < p[i]){
                rank += weight[i];
            }
        }
    }

    return rank;
}

static uint16_t my_rank_ori(const uint8_t o[CUBIES])
{
    uint16_t rank = 0;
    for (uint8_t i = 0; i < 6; ++i){
        rank = (rank << 1) + rank + o[i];
    }

    return rank;
}
#else
/* Host: the author's builders fill the same tables at start-up. */
#include "practice/my_tables.h"
#include "practice/my_pdb.h"
#endif

#ifdef COUNT
static uint64_t expanded;
#define COUNT_NODE() (++expanded)
#else
#define COUNT_NODE() ((void) 0)
#endif

/* ---- Author's search (exercises 4 and 5) ---- */

static uint8_t my_h(uint16_t p, uint16_t o)
{
    uint8_t h1 = my_pdb_p[p];
    uint8_t h2 = my_pdb_o[o];
    return (h1 > h2 ? h1 : h2);
}

/* Field order follows the Stage 4 frame layout (12 bytes, word-aligned):
 * 0 p, 2 o, 4 np, 6 no, 8 face, 9 turn, 10 last_face. In the exercise the
 * order was p, o, face, turn, np, no, last_face; only the order changed.
 */
typedef struct {
    uint16_t p, o; /* 這一層的節點 */
    uint16_t np, no; /* 這一層的下一個子節點的狀態 */
    uint8_t face, turn; /* 這一層的下一個子節點 */
    uint8_t last_face;
} frame_t;

/* 11 frames: a pushed node is unsolved (h >= 1) and unpruned (g + h <=
 * bound), so g <= bound - 1 <= 10. */
static frame_t stack[11];

static int my_search(uint16_t p, uint16_t o, uint8_t bound, uint8_t path[])
{
    frame_t *fr = stack;   /* 目前這一層，等於 &stack[g] */
    uint8_t g = 0;

    /* 根節點：呼叫前 my_solve 已確認不是已解，而且 h <= bound */
    fr->p = fr->np = p;
    fr->o = fr->no = o;
    fr->face = fr->turn = 0;
    fr->last_face = 3;
    COUNT_NODE();

    for (;;) {
        if ( fr->face == 3) {
            if (g == 0)
                return -1;              /* 這一輪 bound 失敗 */
            /* pop：回到上一層 */
            --g;
            fr = &stack[g];
            continue;
        }
        if (fr->turn == 3 || fr->face == fr->last_face) {
            /* 換下一個 face：face + 1，turn 歸零，np/no 重設 */
            ++fr->face;
            fr->turn = 0;
            fr->np = fr->p;
            fr->no = fr->o;
            continue;
        }

        /* 產生下一個子節點 */
        fr->np = my_perm_move[fr->face][fr->np];
        fr->no = my_ori_move[fr->face][fr->no];
        path[g] = (fr->face << 1U) + fr->face + fr->turn;
        ++fr->turn;
        if (fr->np == 0 && fr->no == 0)
            return g + 1;
        if (g + 1 + my_h(fr->np, fr->no) > bound)
            continue;
        /* push：設定下一層的 7 個欄位，fr 往下一層，g + 1 */
        ++g;
        fr = &stack[g];
        fr->face = 0;
        fr->turn = 0;
        fr->last_face = stack[g - 1].face;
        fr->p = fr->np = stack[g - 1].np;
        fr->o = fr->no = stack[g - 1].no;
        COUNT_NODE();
    }
}

static int my_solve(uint16_t p, uint16_t o, uint8_t path[])
{
    if (p == 0 && o == 0)
        return 0;

    uint8_t bound = my_h(p, o);

    while (bound <= 11) {
        int len = my_search(p, o, bound, path);
        if (len >= 0)
            return len;
        ++bound;
    }

    return -1;
}

/* ---- [glue] input validation and replay check ---- */

/* 7 cubie digits '1'..'7' (distinct), 7 twist digits '1'..'3' with the sum
 * of twists 0 mod 3, then the terminator. Fills p[] and o[] 0-based.
 */
static int parse_state(const char *s, uint8_t p[CUBIES], uint8_t o[CUBIES])
{
    uint8_t seen = 0, sum = 0;
    for (int i = 0; i < CUBIES; ++i) {
        uint8_t c = (uint8_t) (s[i] - '1');
        if (c >= CUBIES || (seen >> c) & 1U)
            return 0;
        seen |= (uint8_t) (1U << c);
        p[i] = c;
    }
    for (int i = 0; i < CUBIES; ++i) {
        uint8_t t = (uint8_t) (s[CUBIES + i] - '1');
        if (t >= 3)
            return 0;
        o[i] = t;
        sum = (uint8_t) (sum + t);
    }
    while (sum >= 3)
        sum = (uint8_t) (sum - 3U);
    return s[14] == '\0' && sum == 0;
}

/* T5: apply the returned path with the tables; it must reach (0, 0). A move
 * m = face * 3 + turn is turn + 1 quarter turns of face.
 */
static int replay_ok(uint16_t p, uint16_t o, const uint8_t path[], int len)
{
    for (int k = 0; k < len; ++k) {
        uint8_t face = 0, turns = path[k];
        while (turns >= 3) {
            turns = (uint8_t) (turns - 3U);
            ++face;
        }
        for (uint8_t t = 0; t <= turns; ++t) {
            p = my_perm_move[face][p];
            o = my_ori_move[face][o];
        }
    }
    return p == 0 && o == 0;
}

#ifdef TARGET
/* ---- [glue] target entry: Ripes ecalls, no libc ---- */
extern const char input[];

static void print_str(const char *s)
{
    register const char *a0 __asm__("a0") = s;
    register int a7 __asm__("a7") = 4; /* print string */
    __asm__ volatile("ecall" : : "r"(a0), "r"(a7) : "memory");
}

static void __attribute__((noreturn)) exit_with(int code)
{
    register int a0 __asm__("a0") = code;
    register int a7 __asm__("a7") = 93; /* exit with code */
    __asm__ volatile("ecall" : : "r"(a0), "r"(a7) : "memory");
    for (;;)
        ;
}

void __attribute__((noreturn)) _start(void)
{
    uint8_t p[CUBIES], o[CUBIES], path[11];
    if (!parse_state(input, p, o)) {
        print_str("invalid state\n");
        exit_with(2);
    }
    uint16_t pr = my_rank_perm(p), orr = my_rank_ori(o);
    int len = my_solve(pr, orr, path);
    if (len < 0 || !replay_ok(pr, orr, path, len)) {
        print_str("FAIL\n");
        exit_with(1);
    }
    for (int i = 0; i < len; ++i) {
        if (i)
            print_str(" ");
        print_str(move_names[path[i]]);
    }
    print_str("\n");
    exit_with(0);
}
#else
/* ---- [glue] host entry, same interface as ../solver.c ---- */
#include <stdio.h>

int main(int argc, char **argv)
{
    uint8_t p[CUBIES], o[CUBIES], path[11];
    if (argc != 2 || !parse_state(argv[1], p, o)) {
        fprintf(stderr, "usage: %s PPPPPPPOOOOOOO\n",
                argc > 0 && argv[0] ? argv[0] : "solver_ida");
        return 2;
    }
    my_init_tables();
    uint16_t pr = my_rank_perm(p), orr = my_rank_ori(o);
    int len = my_solve(pr, orr, path);
    if (len < 0 || !replay_ok(pr, orr, path, len)) {
        fputs("FAIL\n", stderr);
        return 1;
    }
    for (int i = 0; i < len; ++i)
        printf("%s%s", i ? " " : "", move_names[path[i]]);
    putchar('\n');
#ifdef COUNT
    fprintf(stderr, "%llu expanded\n", (unsigned long long) expanded);
#endif
    return fflush(stdout) != 0 || ferror(stdout);
}
#endif
