#!/usr/bin/env python3
"""mkgui.py -- flatten the RENDER = 1 build into one file for the Ripes GUI.

    python3 mkgui.py STATE > gui/solver_gui.s

The Ripes GUI assembler (pinned build) provides LED_MATRIX_0_BASE when an LED
Matrix is instantiated, but rejects .if, .include, .section .rodata, .balign
and .globl. This keeps every .if RENDER block, drops everything else the
assembler rejects, inlines render.s and the generated tables, and puts the
input string first. It also rewrites two spellings the Ripes assembler does
not accept into the same values: character constants (' ' -> 32,
'\\n' -> 10, -'1' -> -49) and .ascii strings (-> .byte lists). Every
instruction keeps its opcode and operands.
"""
import re
import sys

state = sys.argv[1]
out = ['# solver_gui.s -- generated by mkgui.py from solver.s, render.s and',
       '# ../stage3/tables.s; do not edit. Input state: ' + state, '',
       '    .data', 'input:', f'    .string "{state}"']


ESC = {'n': 10, 't': 9, '0': 0, '\\': 92, "'": 39}


def char_value(m):
    body = m.group(1)
    return str(ESC[body[1]] if body.startswith('\\') else ord(body))


def fix_code(line):
    code, hash_, comment = line.partition('#')
    m = re.match(r'(\s*)\.ascii\s+"(.*)"\s*$', code)
    if m:
        code = m.group(1) + '.byte ' + ', '.join(str(ord(c)) for c in m.group(2)) + '  '
    code = re.sub(r"'(\\?.)'", char_value, code)
    return code + hash_ + comment


def emit(path, depth=0):
    skip = []  # stack of booleans for nested .if / .ifndef
    for line in open(path):
        line = line.rstrip('\n')
        code = line.split('#', 1)[0].strip()
        if code.startswith('.ifndef'):
            skip.append(True)            # only the RENDER default uses it
            continue
        if code.startswith('.if '):
            skip.append(False)           # .if RENDER: keep in the GUI build
            continue
        if code == '.endif':
            skip.pop()
            continue
        if any(skip):
            continue
        m = re.match(r'\.include\s+"([^"]+)"', code)
        if m:
            emit(m.group(1), depth + 1)
            continue
        if code == '.section .rodata':
            line = '    .data'
        elif re.match(r'\.(balign|globl)\b', code):
            continue
        elif re.match(r'\.equ\s+LED_MATRIX_0_BASE\b', code):
            continue                     # Ripes defines it
        out.append(fix_code(line))


emit('solver.s')
emit('../stage3/tables.s')
print('\n'.join(out))
